site_name: Wagtail XLIFF Translation - Documentation
repo_url: https://github.com/fourdigits/wagtail-xliff-translation
edit_uri: blob/main/docs/
theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'indigo'
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home: index.md
  - Development: development.md
